server:
  port: 4111
spring:
  application:
    name: zuul-server
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone : http://peer1:1111/eureka/
zuul:
  routes:
    api-a :
      path : /api-a/**
      serviceId : HELLO-SERVER